const text = [
"Put on your positive pants",
"Toss your hair in a bun, drink some coffee, put on some gangsta rap and handle it",
"Why become moody when you can shake your booty",
"When something goes wrong in your life, just yell “plot twist” and move on",
"Be a pineapple: stand tall, wear a crown, and be sweet on the inside",
"Was it a bad day? Or was it a bad five minutes that you milked all day?",
"Some see a weed, I see a wish",
"Tell the negative committee that meets inside your head to sit down and shut up",
"Awesome things will happen today if you choose not to be a miserable cow",
"Giving up on your goal because of one setback is like slashing your other three tires because you got a flat",
"Chin up princess or the crown slips",
"If life give you melons you might be dyslexic",
"I love it when the coffee kicks in and I realize what an adorable badass I am going to be today",
"Excuse, I have to go be awesome",
"Think like a proton always positive",
"Tact is the ability to tell someone to go to hell in such a way that they look forward to the trip",
"I am thankful for all those difficult people in my life. They have show me exactly who I do not want to be",
"Not everyone has to like you. Not everyone has taste.",
"We get so worried about being “pretty” let’s be pretty kind, pretty funny, pretty smart, pretty strong.",
"Be brace. Even if you’re not, pretend to be.",
"Get your happy on",
"When shit happens turn it into fertilizer",
"It’s ever too late to get your shit together",
"How to be successful: focus on your own shit",
"Be happy, it drives people crazy",
"Don’t worry about those who talk behind your back, they’re behind you for a reason",
"Compliment people: magnify their strengths, not their weaknesses",
"You can’t make everyone happy. You aren’t a jar of Nutella",
"Life is better when you’re laughing",
"Dear universe, I am totally open to some awesome coming my way",
"Amazing things happen when you distance yourself from negativity",
"If you were able to believe in Santa Claus for like 8 years, you can believe in yourself for like 5 minutes",
"Every time you are able to find some humor in a difficult situation, you win",
"If you have the power to make someone happy, do it. The world needs more of that.",
"Cry a river. Build a bridge. Get over it.",
"Surround yourself with pizza not negativity",
"Don’t ruin a good today by thinking about a bad day yesterday. Let it go",
"The idea is to die young. As late as possible.",
"Remember even your worst days on have 24 hours",
"If you cannot be positive then at least be quiet",
"Nothing can dim the light that shines from within",
"Stop being afraid of what could go wrong and think of what could go right",
"Tell the negative committee that meets inside your head to sit down and shut up",
"What consumes your mind, controls your life",
"Expect nothing and appreciate everything",
"No matter how you feel. Get up, dress up, show up and never give up.",
"Don’t let anyone ever dull your sparkle",
"You may think you’ll never get over it, but you will, and you’ll be fine",
"A negative mind will never give you a positive life",
"Worry about loving yourself, instead of loving the idea of other people loving you",
"Kill them with success and bury them with a smile",
"You have to be odd to be number one",
"Your mistakes don’t define you",
"No beauty shines brighter than that of a good heart",
"Life would be tragic if it weren’t funny",
"Weak people revenge. Strong people forgive. Intelligent people ignore.",
"A secret to happiness is letting every situation be what it is, instead of what you think it should be",
"It’s important to give it all you have while you have the chance",
"Your past is just a story and once you realize this, it has no power over you",
"Be thankful for all the troubles that you don’t have",
"Don’t forget to be awesome",
"And in that moment I swear I still didn’t give a shit",
"To thrive in life you need three bones. A wishbone. A backbone. And a funny bone.",
"Life is 10% of what happens to you and 90% of how you react to it",
"You are good enough, smart enough, beautiful enough, and strong enough. Believe it and never let insecurity run your life.",
"Your vibe attracts your tribe",
"Be somebody who makes everybody feel like a somebody",
"I’m gonna make the rest of my life. The best of my life.",
"It is what it is. Accept it and move on.",
"Never let somebody waste your time, twice.",
"Don’t let your fear of what could happen making nothing happen",
"Broken crayon still color",
"I release all disease from my body and welcome health, love, and happiness into my life",
"Oh, yes you certainly fucking can",
"I persevere. I am relentless. I keep going.",
"Each day, I automatically and successfully get healthier and healthier",
"I love taking good care of myself",
"You can and you will",
"You must believe it to receive it",
"Feelings are just visitors, let them come and go",
"Slow down. Calm down. Don’t worry. Don’t hurry. Trust the process.",
"Doubt kills more dreams than failure ever will.",
"In every moment of my day. I radiate calmness & tranquility. I am still within myself.",
"Take a second to think about how blessed you are.",
"Forgive yourself for your faults and your mistakes and move on",
"Stop looking for happiness in the same place you lost it"
]

export default text
